const mockProductData = [
    {
      id: 1,
      name: "Chaise en bois",
      category: "chaise",
      price: 99.99,
      description: "Chaise en bois avec dossier confortable",
      color: "bois naturel",
      material: "bois",
    },
    {
      id: 2,
      name: "Table en verre",
      category: "table",
      price: 199.99,
      description: "Table en verre élégante pour votre salle à manger",
      color: "transparent",
      material: "verre",
    },
    {
      id: 3,
      name: "Tabouret en métal",
      category: "tabouret",
      price: 49.99,
      description: "Tabouret en métal industriel avec assise en cuir",
      color: "noir",
      material: "métal et cuir",
    },
    {
      id: 4,
      name: "Canapé en tissu",
      category: "canapé",
      price: 499.99,
      description: "Canapé confortable avec revêtement en tissu",
      color: "gris clair",
      material: "tissu et bois",
    },
    {
      id: 5,
      name: "Étagère en métal",
      category: "étagère",
      price: 79.99,
      description: "Étagère moderne en métal pour ranger vos livres",
      color: "noir",
      material: "métal",
    },
    {
      id: 6,
      name: "Lit en cuir",
      category: "lit",
      price: 299.99,
      description: "Lit double en cuir avec tête de lit rembourrée",
      color: "blanc",
      material: "cuir et bois",
    },
    {
      id: 7,
      name: "Bureau en bois",
      category: "bureau",
      price: 149.99,
      description: "Bureau en bois avec tiroirs de rangement",
      color: "chêne",
      material: "bois",
    },
    {
      id: 8,
      name: "Fauteuil en cuir",
      category: "fauteuil",
      price: 199.99,
      description: "Fauteuil en cuir élégant et confortable",
      color: "marron",
      material: "cuir",
    },
    {
      id: 9,
      name: "Lampadaire moderne",
      category: "éclairage",
      price: 69.99,
      description: "Lampadaire avec abat-jour en tissu",
      color: "noir",
      material: "métal et tissu",
    },
    {
      id: 10,
      name: "Miroir mural en argent",
      category: "décoration",
      price: 29.99,
      description: "Miroir mural décoratif avec cadre en argent",
      color: "argent",
      material: "verre et métal",
    },
    // Ajoutez d'autres produits ici
  ];
  
  export default mockProductData;
  