CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  firstName VARCHAR(45),
  lastName VARCHAR(45),
  email VARCHAR(45) UNIQUE,
  password VARCHAR(128),
  isAdmin INTEGER DEFAULT 0
)